# Generated by Django 5.1 on 2024-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_blood_pressure', models.IntegerField()),
                ('high_cholesterol', models.IntegerField()),
                ('cholesterol_check', models.IntegerField()),
                ('body_mass_index', models.FloatField()),
                ('smoker', models.IntegerField()),
                ('stroke', models.IntegerField()),
                ('heart_disease_or_attack', models.IntegerField()),
                ('physical_activity', models.IntegerField()),
                ('consumes_fruits', models.IntegerField()),
                ('consumes_vegetables', models.IntegerField()),
                ('heavy_alcohol_consumption', models.IntegerField()),
                ('health_care_coverage', models.IntegerField()),
                ('no_doctor_because_of_cost', models.IntegerField()),
                ('general_health_self_rating', models.IntegerField()),
                ('mental_health_self_rating', models.IntegerField()),
                ('physical_health_self_rating', models.IntegerField()),
                ('difficulty_walking_stairs', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('age_category', models.IntegerField()),
                ('education_level', models.IntegerField()),
                ('income_scale', models.IntegerField()),
            ],
        ),
    ]
